name: Release

env:
  MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "New release version"
        required: true
      developmentVersion:
        description: "Version to use for the new working copy"
        required: true

jobs:

  release:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: fregante/setup-git-user@v1

      - name: Set up Maven Central
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Prepare release
        run: mvn -B release:prepare -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }} -P release

      - name: Perform release
        run: mvn -B -Darguments="-Dmaven.test.skip=true" release:perform -P release
